/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2025-06-18 04:11:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Docente;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.sample.core.domain.Curso;
import com.sample.core.domain.Materia;

public final class DocenteCursos_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.sample.core.domain.Materia");
    _jspx_imports_classes.add("com.sample.core.domain.Curso");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"es\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <title>Mis Cursos</title>\n");
      out.write("    <!-- Font Awesome -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">\n");
      out.write("    <!-- CSS externo -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/css/cursosDocente.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <div class=\"header\">\n");
      out.write("        <img src=\"https://media.licdn.com/dms/image/v2/C4E0BAQG160jzL6-JqQ/company-logo_200_200/company-logo_200_200/0/1630600241937?e=2147483647&v=beta&t=79lDsncCWhCvwrjJzii6eOau3_IAdsIR1xH7r_7PbVY\" \n");
      out.write("             alt=\"Logo Colegio\" class=\"logo\">\n");
      out.write("        <h1 class=\"nombreColegio\">Instituto Nuestra Señora de Fátima</h1>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"user-bar\">\n");
      out.write("        <div class=\"user-info\">Bienvenido/a profesor, ");
      out.print( session.getAttribute("nombreUsuario") );
      out.write("</div>\n");
      out.write("        <a href=\"");
      out.print( request.getContextPath() );
      out.write("/logout\" class=\"logout-link\">Cerrar sesión</a>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <h2>Mis Cursos</h2>\n");
      out.write("        ");

            Map<Curso, List<Materia>> cursosConMaterias =
                (Map<Curso, List<Materia>>) request.getAttribute("cursosConMaterias");
            if (cursosConMaterias != null && !cursosConMaterias.isEmpty()) {
                for (Map.Entry<Curso, List<Materia>> entry : cursosConMaterias.entrySet()) {
                    Curso curso = entry.getKey();
                    List<Materia> materias = entry.getValue();
        
      out.write("\n");
      out.write("        <button class=\"acordeon\">\n");
      out.write("            ");
      out.print( curso.getNombre() );
      out.write("\n");
      out.write("            <i class=\"fas fa-chevron-down\"></i>\n");
      out.write("        </button>\n");
      out.write("        <div class=\"panel\">\n");
      out.write("            ");
 for (Materia materia : materias) { 
      out.write("\n");
      out.write("            <div class=\"materia-item\">\n");
      out.write("                <a href=\"");
      out.print( request.getContextPath() );
      out.write("/notas?idMateria=");
      out.print( materia.getId() );
      out.write("&idCurso=");
      out.print( curso.getId() );
      out.write("\">- ");
      out.print( materia.getNombre() );
      out.write("</a>\n");
      out.write("            </div>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("        </div>\n");
      out.write("        ");

                }
            } else {
        
      out.write("\n");
      out.write("        <div class=\"no-courses\">\n");
      out.write("            <p>No tienes cursos asignados.</p>\n");
      out.write("        </div>\n");
      out.write("        ");

            }
        
      out.write("\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <script>\n");
      out.write("        document.querySelectorAll('.acordeon').forEach(button => {\n");
      out.write("            button.nextElementSibling.style.display = 'none';\n");
      out.write("            button.addEventListener('click', function() {\n");
      out.write("                document.querySelectorAll('.panel').forEach(panel => {\n");
      out.write("                    if (panel !== this.nextElementSibling) {\n");
      out.write("                        panel.style.display = 'none';\n");
      out.write("                        panel.previousElementSibling.classList.remove('active');\n");
      out.write("                    }\n");
      out.write("                });\n");
      out.write("                this.classList.toggle('active');\n");
      out.write("                const panel = this.nextElementSibling;\n");
      out.write("                panel.style.display = panel.style.display === 'block' ? 'none' : 'block';\n");
      out.write("            });\n");
      out.write("        });\n");
      out.write("    </script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
