/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2025-06-18 03:32:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Docente;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import com.sample.core.domain.notas;

public final class NotasDocente_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.sample.core.domain.notas");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("<title>Notas de Alumnos</title>\n");
      out.write("<link rel=\"stylesheet\" href=\"css/notas.css\">\n");
      out.write("<script src=\"scripts/jquery/jquery-3.7.1.min.js\"></script>\n");
      out.write("<script src=\"scripts/eliminarNotas.js\"></script>\n");
      out.write("<script src=\"scripts/guardarNotas.js\"></script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<div class=\"header\">\n");
      out.write("\t\t<button class=\"back-button\" onclick=\"history.back()\">\n");
      out.write("\t\t\t<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\">\n");
      out.write("                <path\n");
      out.write("\t\t\t\t\td=\"M20 11H7.83l5.59-5.59L12 4l-8 8 8 8 1.41-1.41L7.83 13H20v-2z\" />\n");
      out.write("            </svg>\n");
      out.write("\t\t</button>\n");
      out.write("\t\t<img\n");
      out.write("\t\t\tsrc=\"https://media.licdn.com/dms/image/v2/C4E0BAQG160jzL6-JqQ/company-logo_200_200/company-logo_200_200/0/1630600241937?e=2147483647&v=beta&t=79lDsncCWhCvwrjJzii6eOau3_IAdsIR1xH7r_7PbVY\"\n");
      out.write("\t\t\talt=\"Logo Colegio\" class=\"logo\">\n");
      out.write("\t\t<h1 class=\"nombreColegio\">Instituto Nuestra Señora de Fatima</h1>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\t<div class=\"container\">\n");
      out.write("\t\t<h2>Notas de Alumnos</h2>\n");
      out.write("\n");
      out.write("\t\t<div class=\"table-container\">\n");
      out.write("\t\t\t<table>\n");
      out.write("\t\t\t\t<thead>\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t<th class=\"col-nombre\">Nombre</th>\n");
      out.write("\t\t\t\t\t\t<th class=\"col-apellido\">Apellido</th>\n");
      out.write("\t\t\t\t\t\t<th class=\"col-nota\">Nota 1</th>\n");
      out.write("\t\t\t\t\t\t<th class=\"col-nota\">Nota 2</th>\n");
      out.write("\t\t\t\t\t\t<th class=\"col-nota\">Nota 3</th>\n");
      out.write("\t\t\t\t\t\t<th class=\"col-promedio\">Promedio</th>\n");
      out.write("\t\t\t\t\t\t<th class=\"col-acciones\">Acciones</th>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t</thead>\n");
      out.write("\t\t\t\t<tbody>\n");
      out.write("\t\t\t\t\t");

					List<notas> lista = (List<notas>) request.getAttribute("notas");
					if (lista != null && !lista.isEmpty()) {
						for (notas n : lista) {
					
      out.write("\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(n.getNombreAlumno());
      out.write("</td>\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(n.getApellidoAlumno());
      out.write("</td>\n");
      out.write("\t\t\t\t\t\t<td><input type=\"number\" class=\"nota1\"\n");
      out.write("\t\t\t\t\t\t\tvalue=\"");
      out.print(n.getNota1());
      out.write("\" min=\"0\" max=\"10\" step=\"1\"\n");
      out.write("\t\t\t\t\t\t\toninput=\"if (this.value==='') return;\n");
      out.write("             this.value = Math.max(0, Math.min(10, Number(this.value)));\n");
      out.write("           \" /></td>\n");
      out.write("\t\t\t\t\t\t<td><input type=\"number\" class=\"nota2\"\n");
      out.write("\t\t\t\t\t\t\tvalue=\"");
      out.print(n.getNota2());
      out.write("\" min=\"0\" max=\"10\" step=\"1\"\n");
      out.write("\t\t\t\t\t\t\toninput=\"\n");
      out.write("             if (this.value==='') return;\n");
      out.write("             this.value = Math.max(0, Math.min(10, Number(this.value)));\n");
      out.write("           \" /></td>\n");
      out.write("\t\t\t\t\t\t<td><input type=\"number\" class=\"nota3\"\n");
      out.write("\t\t\t\t\t\t\tvalue=\"");
      out.print(n.getNota3());
      out.write("\" min=\"0\" max=\"10\" step=\"1\"\n");
      out.write("\t\t\t\t\t\t\toninput=\"\n");
      out.write("             if (this.value==='') return;\n");
      out.write("             this.value = Math.max(0, Math.min(10, Number(this.value)));\n");
      out.write("           \" /></td>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<td class=\"promedio-cell\"><span class=\"promedio-value\">");
      out.print(n.getPromedio());
      out.write("</span>\n");
      out.write("\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t<td class=\"acciones-cell\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"acciones-container\">\n");
      out.write("\t\t\t\t\t\t\t\t<button class=\"guardarBtn\" data-id=\"");
      out.print(n.getIdAlumno());
      out.write("\">Guardar</button>\n");
      out.write("\t\t\t\t\t\t\t\t<button class=\"eliminar-btn\" data-id=\"");
      out.print(n.getIdAlumno());
      out.write("\">Eliminar</button>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t");

					}
					} else {
					
      out.write("\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t<td colspan=\"7\">No hay notas disponibles.</td>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t");

					}
					
      out.write("\n");
      out.write("\t\t\t\t</tbody>\n");
      out.write("\t\t\t</table>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
