/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
<<<<<<< Updated upstream
 * Generated at: 2025-06-16 23:36:27 UTC
=======
 * Generated at: 2025-06-17 01:28:00 UTC
>>>>>>> Stashed changes
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import com.sample.core.domain.notas;

public final class NotasDocente_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.sample.core.domain.notas");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

<<<<<<< Updated upstream
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <title>Notas de Alumnos</title>\n");
      out.write("    <script src=\"scripts/jquery/jquery-3.7.1.min.js\"></script>\n");
      out.write("    <script src=\"scripts/eliminarNotas.js\"></script>\n");
      out.write("\t<script src=\"scripts/guardarNotas.js\"></script>\n");
      out.write("    <style>\n");
      out.write("       body {\n");
      out.write("           font-family: Arial, sans-serif;\n");
      out.write("           background-color: #ffffff;\n");
      out.write("           margin: 0;\n");
      out.write("           padding: 0;\n");
      out.write("           color: #333;\n");
      out.write("       }\n");
      out.write("       .header {\n");
      out.write("           display: flex;\n");
      out.write("           align-items: center;\n");
      out.write("           gap: 20px;\n");
      out.write("           padding: 20px;\n");
      out.write("           margin-left: 20px;\n");
      out.write("       }\n");
      out.write("       .logo {\n");
      out.write("           width: 100px;\n");
      out.write("           height: auto;\n");
      out.write("       }\n");
      out.write("       .nombreColegio {\n");
      out.write("           font-size: 24px;\n");
      out.write("           color: #333;\n");
      out.write("           margin: 0;\n");
      out.write("       }\n");
      out.write("       h2 {\n");
      out.write("           text-align: center;\n");
      out.write("           color: #333;\n");
      out.write("           margin: 30px 0 20px 0;\n");
      out.write("           font-size: 28px;\n");
      out.write("           font-weight: 600;\n");
      out.write("       }\n");
      out.write("       table {\n");
      out.write("           width: 80%;\n");
      out.write("           margin: 0 auto 50px auto;\n");
      out.write("           border-collapse: collapse;\n");
      out.write("           border-radius: 12px;\n");
      out.write("           box-shadow: 0 4px 10px rgba(0, 0, 0, 0.1);\n");
      out.write("           overflow: hidden;\n");
      out.write("       }\n");
      out.write("       th {\n");
      out.write("           background-color: #ff0000ea;\n");
      out.write("           color: white;\n");
      out.write("           padding: 12px 15px;\n");
      out.write("           text-align: center;\n");
      out.write("           font-weight: 700;\n");
      out.write("           font-size: 16px;\n");
      out.write("       }\n");
      out.write("       td {\n");
      out.write("           padding: 12px 15px;\n");
      out.write("           text-align: center;\n");
      out.write("           border-bottom: 1px solid #e0e0e0;\n");
      out.write("           font-size: 15px;\n");
      out.write("       }\n");
      out.write("       tbody tr:nth-child(even) {\n");
      out.write("           background-color: #f8f9fa;\n");
      out.write("       }\n");
      out.write("       td[colspan=\"6\"] {\n");
      out.write("           padding: 20px;\n");
      out.write("           text-align: center;\n");
      out.write("           color: #721c24;\n");
      out.write("           background-color: #f8d7da;\n");
      out.write("           font-weight: 600;\n");
      out.write("           border-radius: 0 0 12px 12px;\n");
      out.write("       }\n");
      out.write("       tbody tr:hover {\n");
      out.write("           background-color: #ffeaea;\n");
      out.write("           cursor: default;\n");
      out.write("       }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("    <div class=\"header\">\n");
      out.write("        <img src=\"https://media.licdn.com/dms/image/v2/C4E0BAQG160jzL6-JqQ/company-logo_200_200/company-logo_200_200/0/1630600241937?e=2147483647&v=beta&t=79lDsncCWhCvwrjJzii6eOau3_IAdsIR1xH7r_7PbVY\" alt=\"Logo Colegio\" class=\"logo\">\n");
      out.write("        <h1 class=\"nombreColegio\">Instituto Nuestra Seniora de Fatima</h1>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <h2>Notas de Alumnos</h2>\n");
      out.write("\n");
      out.write("    <table>\n");
      out.write("<thead>\n");
      out.write("    <tr>\n");
      out.write("        <th>Nombre</th>\n");
      out.write("        <th>Apellido</th>\n");
      out.write("        <th>Nota 1</th>\n");
      out.write("        <th>Nota 2</th>\n");
      out.write("        <th>Nota 3</th>\n");
      out.write("        <th>Promedio</th>\n");
      out.write("        <th>Eliminar</th> <!-- una nueva columna agregue aqui -->\n");
      out.write("    </tr>\n");
      out.write("</thead>\n");
      out.write("<tbody>\n");
=======
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Notas de Alumnos</title>\r\n");
      out.write("    <script src=\"scripts/jquery/jquery-3.7.1.min.js\"></script>\r\n");
      out.write("\t<script src=\"scripts/guardarNotas.js\"></script>\r\n");
      out.write("    <style>\r\n");
      out.write("       body {\r\n");
      out.write("           font-family: Arial, sans-serif;\r\n");
      out.write("           background-color: #ffffff;\r\n");
      out.write("           margin: 0;\r\n");
      out.write("           padding: 0;\r\n");
      out.write("           color: #333;\r\n");
      out.write("       }\r\n");
      out.write("       .header {\r\n");
      out.write("           display: flex;\r\n");
      out.write("           align-items: center;\r\n");
      out.write("           gap: 20px;\r\n");
      out.write("           padding: 20px;\r\n");
      out.write("           margin-left: 20px;\r\n");
      out.write("       }\r\n");
      out.write("       .logo {\r\n");
      out.write("           width: 100px;\r\n");
      out.write("           height: auto;\r\n");
      out.write("       }\r\n");
      out.write("       .nombreColegio {\r\n");
      out.write("           font-size: 24px;\r\n");
      out.write("           color: #333;\r\n");
      out.write("           margin: 0;\r\n");
      out.write("       }\r\n");
      out.write("       h2 {\r\n");
      out.write("           text-align: center;\r\n");
      out.write("           color: #333;\r\n");
      out.write("           margin: 30px 0 20px 0;\r\n");
      out.write("           font-size: 28px;\r\n");
      out.write("           font-weight: 600;\r\n");
      out.write("       }\r\n");
      out.write("       table {\r\n");
      out.write("           width: 80%;\r\n");
      out.write("           margin: 0 auto 50px auto;\r\n");
      out.write("           border-collapse: collapse;\r\n");
      out.write("           border-radius: 12px;\r\n");
      out.write("           box-shadow: 0 4px 10px rgba(0, 0, 0, 0.1);\r\n");
      out.write("           overflow: hidden;\r\n");
      out.write("       }\r\n");
      out.write("       th {\r\n");
      out.write("           background-color: #ff0000ea;\r\n");
      out.write("           color: white;\r\n");
      out.write("           padding: 12px 15px;\r\n");
      out.write("           text-align: center;\r\n");
      out.write("           font-weight: 700;\r\n");
      out.write("           font-size: 16px;\r\n");
      out.write("       }\r\n");
      out.write("       td {\r\n");
      out.write("           padding: 12px 15px;\r\n");
      out.write("           text-align: center;\r\n");
      out.write("           border-bottom: 1px solid #e0e0e0;\r\n");
      out.write("           font-size: 15px;\r\n");
      out.write("       }\r\n");
      out.write("       tbody tr:nth-child(even) {\r\n");
      out.write("           background-color: #f8f9fa;\r\n");
      out.write("       }\r\n");
      out.write("       td[colspan=\"6\"] {\r\n");
      out.write("           padding: 20px;\r\n");
      out.write("           text-align: center;\r\n");
      out.write("           color: #721c24;\r\n");
      out.write("           background-color: #f8d7da;\r\n");
      out.write("           font-weight: 600;\r\n");
      out.write("           border-radius: 0 0 12px 12px;\r\n");
      out.write("       }\r\n");
      out.write("       tbody tr:hover {\r\n");
      out.write("           background-color: #ffeaea;\r\n");
      out.write("           cursor: default;\r\n");
      out.write("       }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"header\">\r\n");
      out.write("        <img src=\"https://media.licdn.com/dms/image/v2/C4E0BAQG160jzL6-JqQ/company-logo_200_200/company-logo_200_200/0/1630600241937?e=2147483647&v=beta&t=79lDsncCWhCvwrjJzii6eOau3_IAdsIR1xH7r_7PbVY\" alt=\"Logo Colegio\" class=\"logo\">\r\n");
      out.write("        <h1 class=\"nombreColegio\">Instituto Nuestra Seniora de Fatima</h1>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <h2>Notas de Alumnos</h2>\r\n");
      out.write("\r\n");
      out.write("    <table>\r\n");
      out.write("        <thead>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <th>Nombre</th>\r\n");
      out.write("                <th>Apellido</th>\r\n");
      out.write("                <th>Nota 1</th>\r\n");
      out.write("                <th>Nota 2</th>\r\n");
      out.write("                <th>Nota 3</th>\r\n");
      out.write("                <th>Promedio</th>\r\n");
      out.write("            </tr>\r\n");
      out.write("        </thead>\r\n");
      out.write("<tbody>\r\n");
>>>>>>> Stashed changes

    List<notas> lista = (List<notas>) request.getAttribute("notas");
    if (lista != null && !lista.isEmpty()) {
        for (notas n : lista) {

      out.write("\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>");
      out.print( n.getNombreAlumno() );
      out.write("</td>\r\n");
      out.write("                <td>");
      out.print( n.getApellidoAlumno() );
<<<<<<< Updated upstream
      out.write("</td>\n");
      out.write("                <td><input type=\"number\" class=\"nota1\" value=\"");
      out.print( n.getNota1() );
      out.write("\" /></td>\n");
      out.write("                <td><input type=\"number\" class=\"nota2\" value=\"");
      out.print( n.getNota2() );
      out.write("\" /></td>\n");
      out.write("                <td><input type=\"number\" class=\"nota3\" value=\"");
      out.print( n.getNota3() );
      out.write("\" /></td>\n");
      out.write("                <td>\n");
      out.write("                    ");
      out.print( n.getPromedio() );
      out.write("\n");
      out.write("                    <button class=\"guardarBtn\" data-id=\"");
      out.print( n.getIdAlumno() );
      out.write("\">Guardar</button>\n");
      out.write("                </td>\n");
      out.write("                <td>\n");
      out.write("                    <button class=\"eliminar-btn\" data-id=\"");
      out.print( n.getIdAlumno() );
      out.write("\">Eliminar</button>\n");
      out.write("                </td>\n");
      out.write("            </tr>\n");
=======
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"number\" class=\"nota1\" value=\"");
      out.print( n.getNota1() );
      out.write("\" /></td>\r\n");
      out.write("\t\t\t\t<td><input type=\"number\" class=\"nota2\" value=\"");
      out.print( n.getNota2() );
      out.write("\" /></td>\r\n");
      out.write("\t\t\t\t<td><input type=\"number\" class=\"nota3\" value=\"");
      out.print( n.getNota3() );
      out.write("\" /></td>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("    \t\t\t");
      out.print( n.getPromedio() );
      out.write("\r\n");
      out.write("    \t\t\t<button class=\"guardarBtn\" data-id=\"");
      out.print( n.getIdAlumno() );
      out.write("\">Guardar</button>\r\n");
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("            </tr>\r\n");
>>>>>>> Stashed changes

        }
    } else {

<<<<<<< Updated upstream
      out.write("\n");
      out.write("    <tr>\n");
      out.write("        <td colspan=\"7\">No hay notas disponibles.</td>\n");
      out.write("    </tr>\n");
=======
      out.write("\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td colspan=\"6\">No hay notas disponibles.</td>\r\n");
      out.write("        </tr>\r\n");
>>>>>>> Stashed changes

    }

      out.write("\r\n");
      out.write("</tbody>\r\n");
      out.write("    </table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
