/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2025-06-16 21:56:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.sample.core.domain.Curso;
import com.sample.core.domain.Materia;

public final class RectorCursos_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.sample.core.domain.Materia");
    _jspx_imports_classes.add("com.sample.core.domain.Curso");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Cursos del Rector</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">\r\n");
      out.write("   <style>\r\n");
      out.write("        /* Estilos generales */\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: Arial, sans-serif;\r\n");
      out.write("            background-color: #ffffff;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /* Logo y header */\r\n");
      out.write("        .header {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 20px;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            margin-left: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .logo {\r\n");
      out.write("            width: 100px;\r\n");
      out.write("            height: auto;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .nombreColegio {\r\n");
      out.write("            font-size: 24px;\r\n");
      out.write("            color: #333;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /* Contenedor principal */\r\n");
      out.write("        .container {\r\n");
      out.write("            max-width: 800px;\r\n");
      out.write("            margin: 30px auto;\r\n");
      out.write("            background-color: #ffffff;\r\n");
      out.write("            padding: 30px;\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            box-shadow: 0 4px 10px rgba(0, 0, 0, 0.1);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /* Títulos */\r\n");
      out.write("        h1, h2 {\r\n");
      out.write("            color: #333;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /* Barra de usuario */\r\n");
      out.write("        .user-bar {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            padding: 15px 30px;\r\n");
      out.write("            background-color: #f8f9fa;\r\n");
      out.write("            border-bottom: 1px solid #e9ecef;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .user-info {\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            color: #333;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .logout-link {\r\n");
      out.write("            color: #ff0000ea;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            transition: color 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .logout-link:hover {\r\n");
      out.write("            color: #b30600;\r\n");
      out.write("            text-decoration: underline;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /* Acordeón de cursos */\r\n");
      out.write("        .acordeon {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            padding: 15px;\r\n");
      out.write("            border: none;\r\n");
      out.write("            text-align: left;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            margin: 8px 0;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            background-color: #ff0000ea;\r\n");
      out.write("            color: white;\r\n");
      out.write("            transition: background-color 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .acordeon:hover {\r\n");
      out.write("            background-color: #b30600;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .acordeon i {\r\n");
      out.write("            margin-left: 10px;\r\n");
      out.write("            transition: transform 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .acordeon.active i {\r\n");
      out.write("            transform: rotate(180deg);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .panel {\r\n");
      out.write("            padding: 0 20px;\r\n");
      out.write("            display: none;\r\n");
      out.write("            background-color: #f8f9fa;\r\n");
      out.write("            border-left: 4px solid #ff0000ea;\r\n");
      out.write("            border-radius: 0 0 8px 8px;\r\n");
      out.write("            margin-bottom: 15px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .materia-item {\r\n");
      out.write("            padding: 12px;\r\n");
      out.write("            border-bottom: 1px solid #e9ecef;\r\n");
      out.write("            font-size: 15px;\r\n");
      out.write("            color: #555;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .no-courses {\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            background-color: #f8d7da;\r\n");
      out.write("            color: #721c24;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"header\">\r\n");
      out.write("        <img src=\"https://media.licdn.com/dms/image/v2/C4E0BAQG160jzL6-JqQ/company-logo_200_200/company-logo_200_200/0/1630600241937?e=2147483647&v=beta&t=79lDsncCWhCvwrjJzii6eOau3_IAdsIR1xH7r_7PbVY\" alt=\"Logo Colegio\" class=\"logo\">\r\n");
      out.write("        <h1 class=\"nombreColegio\">Instituto Nuestra Señora de Fátima</h1>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"user-bar\">\r\n");
      out.write("        <div class=\"user-info\">Bienvenido rector, ");
      out.print( session.getAttribute("nombreUsuario") );
      out.write("</div>\r\n");
      out.write("        <a href=\"");
      out.print( request.getContextPath() );
      out.write("/logout\" class=\"logout-link\">Cerrar sesión</a>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <h2>Todos los Cursos y Materias</h2>\r\n");
      out.write("        \r\n");
      out.write("        ");

        Map<Curso, List<Materia>> todosLosCursosConMaterias = (Map<Curso, List<Materia>>) request.getAttribute("todosLosCursosConMaterias");
        if (todosLosCursosConMaterias != null && !todosLosCursosConMaterias.isEmpty()) {
            for (Map.Entry<Curso, List<Materia>> entry : todosLosCursosConMaterias.entrySet()) {
                Curso curso = entry.getKey();
                List<Materia> materias = entry.getValue();
        
      out.write("\r\n");
      out.write("                <button class=\"acordeon\">\r\n");
      out.write("                    ");
      out.print( curso.getNombre() );
      out.write("\r\n");
      out.write("                    <i class=\"fas fa-chevron-down\"></i>\r\n");
      out.write("                </button>\r\n");
      out.write("                <div class=\"panel\">\r\n");
      out.write("                    ");
 for (Materia materia : materias) { 
      out.write("\r\n");
      out.write("                        <div class=\"materia-item\">\r\n");
      out.write("                            <a href=\"");
      out.print( request.getContextPath() );
      out.write("/notas?idMateria=");
      out.print( materia.getId() );
      out.write("&idCurso=");
      out.print( curso.getId() );
      out.write("\">\r\n");
      out.write("                                - ");
      out.print( materia.getNombre() );
      out.write("\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("        ");

            }
        } else {
        
      out.write("\r\n");
      out.write("            <div class=\"no-courses\">\r\n");
      out.write("                <p>No hay cursos disponibles.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        ");

        }
        
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        document.querySelectorAll('.acordeon').forEach(button => {\r\n");
      out.write("            button.nextElementSibling.style.display = 'none';\r\n");
      out.write("            \r\n");
      out.write("            button.addEventListener('click', function() {\r\n");
      out.write("                document.querySelectorAll('.panel').forEach(panel => {\r\n");
      out.write("                    if (panel !== this.nextElementSibling) {\r\n");
      out.write("                        panel.style.display = 'none';\r\n");
      out.write("                        panel.previousElementSibling.classList.remove('active');\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("                \r\n");
      out.write("                this.classList.toggle('active');\r\n");
      out.write("                const panel = this.nextElementSibling;\r\n");
      out.write("                panel.style.display = panel.style.display === 'block' ? 'none' : 'block';\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
